### ISSUE TITLE
I meet a issue about the difference of input and weight type.

### ISSUE THREAD

**Issue by goodgoodxu** [nobodyplayer1/VM-UNetV2#4]
when I train this project, there is a RuntimeError like this:
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same.

**Comment by simzhangbest** [comment]
这个可能是由于你的输入 和模型不匹配，请贴一下更多的日志

**Comment by goodgoodxu** [comment]
> 这个可能是由于你的输入 和模型不匹配，请贴一下更多的日志

我目前想在gpu上运行，所以需要使用cuda。根据这个报错，我觉得是weight type没有是设置成gpu，但是我不知道如何去改。（关于gpu，我仅做过一次修改：为了使用我的gpu，我将config_settings_v2.py里的gpu_id设置成了0
![image](https://github.com/nobodyplayer1/VM-UNetV2/assets/86276912/12eb6a1d-1ccb-4206-82e2-aa43c49dd8b1)
）

**Comment by simzhangbest** [comment]
> > 这个可能是由于你的输入 和模型不匹配，请贴一下更多的日志
> 
> 我目前想在gpu上运行，所以需要使用cuda。根据这个报错，我觉得是weight type没有是设置成gpu，但是我不知道如何去改。（关于gpu，我仅做过一次修改：为了使用我的gpu，我将config_settings_v2.py里的gpu_id设置成了0 ![image](https://private-user-images.githubusercontent.com/86276912/320396206-12eb6a1d-1ccb-4206-82e2-aa43c49dd8b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjMwOTksIm5iZiI6MTcxMjU2Mjc5OSwicGF0aCI6Ii84NjI3NjkxMi8zMjAzOTYyMDYtMTJlYjZhMWQtMWNjYi00MjA2LTgyZTItYWE0M2M0OWRkOGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA3NTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYmVhNDEwNDhjMTRkY2JkYzA0YjBlM2ZkNWZkOWY0N2FjY2I1MGJmMTM3YWE1MTE0MzQ0MzZmYTI2Nzk3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d84CwMfWAcgs2xokrkGIM9izCtRdpGYud6abeOtOmyY) ）

你有正确下载VMamba的权重文件吗？

**Comment by goodgoodxu** [comment]
> > > 这个可能是由于你的输入 和模型不匹配，请贴一下更多的日志
> > 
> > 
> > 我目前想在gpu上运行，所以需要使用cuda。根据这个报错，我觉得是weight type没有是设置成gpu，但是我不知道如何去改。（关于gpu，我仅做过一次修改：为了使用我的gpu，我将config_settings_v2.py里的gpu_id设置成了0 ![image](https://private-user-images.githubusercontent.com/86276912/320396206-12eb6a1d-1ccb-4206-82e2-aa43c49dd8b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjMwOTksIm5iZiI6MTcxMjU2Mjc5OSwicGF0aCI6Ii84NjI3NjkxMi8zMjAzOTYyMDYtMTJlYjZhMWQtMWNjYi00MjA2LTgyZTItYWE0M2M0OWRkOGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA3NTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYmVhNDEwNDhjMTRkY2JkYzA0YjBlM2ZkNWZkOWY0N2FjY2I1MGJmMTM3YWE1MTE0MzQ0MzZmYTI2Nzk3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d84CwMfWAcgs2xokrkGIM9izCtRdpGYud6abeOtOmyY) ）
> 
> 你有正确下载VMamba的权重文件吗？

您好，我下载了三个文件，并把它们全部放在了，预训练权重那个文件夹内。
![image](https://github.com/nobodyplayer1/VM-UNetV2/assets/86276912/09c3fb19-d4a4-4d62-b407-9af16b48aa38)

**Comment by simzhangbest** [comment]
> > > > 这个可能是由于你的输入 和模型不匹配，请贴一下更多的日志
> > > 
> > > 
> > > 我目前想在gpu上运行，所以需要使用cuda。根据这个报错，我觉得是weight type没有是设置成gpu，但是我不知道如何去改。（关于gpu，我仅做过一次修改：为了使用我的gpu，我将config_settings_v2.py里的gpu_id设置成了0 ![image](https://private-user-images.githubusercontent.com/86276912/320396206-12eb6a1d-1ccb-4206-82e2-aa43c49dd8b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjMwOTksIm5iZiI6MTcxMjU2Mjc5OSwicGF0aCI6Ii84NjI3NjkxMi8zMjAzOTYyMDYtMTJlYjZhMWQtMWNjYi00MjA2LTgyZTItYWE0M2M0OWRkOGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA3NTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYmVhNDEwNDhjMTRkY2JkYzA0YjBlM2ZkNWZkOWY0N2FjY2I1MGJmMTM3YWE1MTE0MzQ0MzZmYTI2Nzk3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d84CwMfWAcgs2xokrkGIM9izCtRdpGYud6abeOtOmyY) ）
> > 
> > 
> > 你有正确下载VMamba的权重文件吗？
> 
> 您好，我下载了三个文件，并把它们全部放在了，预训练权重那个文件夹内。 ![image](https://private-user-images.githubusercontent.com/86276912/320398655-09c3fb19-d4a4-4d62-b407-9af16b48aa38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjMzNzIsIm5iZiI6MTcxMjU2MzA3MiwicGF0aCI6Ii84NjI3NjkxMi8zMjAzOTg2NTUtMDljM2ZiMTktZDRhNC00ZDYyLWI0MDctOWFmMTZiNDhhYTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA3NTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZTYwNzBjYjg4ZGUzZWIxN2M1MzQ2MjgyNGNlOTQ5MzM1MTQ3ZGI3YWM3NzEwZGYzYTZhZDE0NzMxYTAxMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1BWHbLmiuqrjq4qK_dnoaNRsDKpguIrv8AB7rD-xciA)

我想我知道你的原因了，请不要使用window 去做实验，这个vmamba 好像也不支持windows ,最好使用linux 服务器去跑实验

**Comment by goodgoodxu** [comment]
> > > > > 这个可能是由于你的输入 和模型不匹配，请贴一下更多的日志
> > > > 
> > > > 
> > > > 我目前想在gpu上运行，所以需要使用cuda。根据这个报错，我觉得是weight type没有是设置成gpu，但是我不知道如何去改。（关于gpu，我仅做过一次修改：为了使用我的gpu，我将config_settings_v2.py里的gpu_id设置成了0 ![image](https://private-user-images.githubusercontent.com/86276912/320396206-12eb6a1d-1ccb-4206-82e2-aa43c49dd8b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjMwOTksIm5iZiI6MTcxMjU2Mjc5OSwicGF0aCI6Ii84NjI3NjkxMi8zMjAzOTYyMDYtMTJlYjZhMWQtMWNjYi00MjA2LTgyZTItYWE0M2M0OWRkOGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA3NTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYmVhNDEwNDhjMTRkY2JkYzA0YjBlM2ZkNWZkOWY0N2FjY2I1MGJmMTM3YWE1MTE0MzQ0MzZmYTI2Nzk3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d84CwMfWAcgs2xokrkGIM9izCtRdpGYud6abeOtOmyY) ）
> > > 
> > > 
> > > 你有正确下载VMamba的权重文件吗？
> > 
> > 
> > 您好，我下载了三个文件，并把它们全部放在了，预训练权重那个文件夹内。 ![image](https://private-user-images.githubusercontent.com/86276912/320398655-09c3fb19-d4a4-4d62-b407-9af16b48aa38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjMzNzIsIm5iZiI6MTcxMjU2MzA3MiwicGF0aCI6Ii84NjI3NjkxMi8zMjAzOTg2NTUtMDljM2ZiMTktZDRhNC00ZDYyLWI0MDctOWFmMTZiNDhhYTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA3NTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZTYwNzBjYjg4ZGUzZWIxN2M1MzQ2MjgyNGNlOTQ5MzM1MTQ3ZGI3YWM3NzEwZGYzYTZhZDE0NzMxYTAxMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1BWHbLmiuqrjq4qK_dnoaNRsDKpguIrv8AB7rD-xciA)
> 
> 我想我知道你的原因了，请不要使用window 去做实验，这个vmamba 好像也不支持windows ,最好使用linux 服务器去跑实验

嗷嗷，我明白了，非常感谢您。我将要尝试在linux下运行

**Comment by simzhangbest** [comment]
> > > > > > 这个可能是由于你的输入 和模型不匹配，请贴一下更多的日志
> > > > > 
> > > > > 
> > > > > 我目前想在gpu上运行，所以需要使用cuda。根据这个报错，我觉得是weight type没有是设置成gpu，但是我不知道如何去改。（关于gpu，我仅做过一次修改：为了使用我的gpu，我将config_settings_v2.py里的gpu_id设置成了0 ![image](https://private-user-images.githubusercontent.com/86276912/320396206-12eb6a1d-1ccb-4206-82e2-aa43c49dd8b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjMwOTksIm5iZiI6MTcxMjU2Mjc5OSwicGF0aCI6Ii84NjI3NjkxMi8zMjAzOTYyMDYtMTJlYjZhMWQtMWNjYi00MjA2LTgyZTItYWE0M2M0OWRkOGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA3NTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYmVhNDEwNDhjMTRkY2JkYzA0YjBlM2ZkNWZkOWY0N2FjY2I1MGJmMTM3YWE1MTE0MzQ0MzZmYTI2Nzk3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d84CwMfWAcgs2xokrkGIM9izCtRdpGYud6abeOtOmyY) ）
> > > > 
> > > > 
> > > > 你有正确下载VMamba的权重文件吗？
> > > 
> > > 
> > > 您好，我下载了三个文件，并把它们全部放在了，预训练权重那个文件夹内。 ![image](https://private-user-images.githubusercontent.com/86276912/320398655-09c3fb19-d4a4-4d62-b407-9af16b48aa38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjMzNzIsIm5iZiI6MTcxMjU2MzA3MiwicGF0aCI6Ii84NjI3NjkxMi8zMjAzOTg2NTUtMDljM2ZiMTktZDRhNC00ZDYyLWI0MDctOWFmMTZiNDhhYTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA3NTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZTYwNzBjYjg4ZGUzZWIxN2M1MzQ2MjgyNGNlOTQ5MzM1MTQ3ZGI3YWM3NzEwZGYzYTZhZDE0NzMxYTAxMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1BWHbLmiuqrjq4qK_dnoaNRsDKpguIrv8AB7rD-xciA)
> > 
> > 
> > 我想我知道你的原因了，请不要使用window 去做实验，这个vmamba 好像也不支持windows ,最好使用linux 服务器去跑实验
> 
> 嗷嗷，我明白了，非常感谢您。我将要尝试在linux下运行

可以关闭这个issus 了
